### ISSUE TITLE
[DOCUMENTATION] - Obfuscation Crash.

### ISSUE THREAD

**Issue by therealOri** [Traumatism/Dropper#1]
# Obfuscation "bomb". (Crash/Lockup/Freeze)
So I decided to try out obfuscating a file multiple times and then ran the file. It froze/locked up my computer/laptop.
So I thought I'd share it.

<br />
<br />

# Steps to reproduce:
- Obfuscate a python file like normal. (Preferably a large file)
- Obfuscate the obfuscated file. (obf_obf_file.py)
- Do this a couple more times. (obf_obf_obf_obf.....etc_file.py. The more the better.)
- Run python3 <insert ***VERY*** obfuscated file>.
- Computer will lock up/freeze. Need to restart.

<br />
<br />

# System Information:
- OS: Manjaro Linux x86_64
- Kernel: 5.10.93-1-MANJARO
- CPU: Intel i7-8565U (8) @ 4.600GHz
- RAM: 8GB

Note: I don't doubt that if you obfuscate one file enough times, it'll still work on higher end computers. (Feel free to test)
I also didn't see the "Discussions" tab enabled so I thought I'd just drop this here in the "issues" for now.

**Comment by lhitori** [comment]
sorry to answer to a that long message with a that short message but:

ty, fixed it.
