### ISSUE TITLE
Deobfuscated

### ISSUE THREAD

**Issue by ImInTheICU** [Traumatism/Dropper#7]
![image](https://user-images.githubusercontent.com/111275373/200115450-b8ea61fe-72b7-41b4-af0e-54ecc836b87a.png)
Asked a friend to deobfuscate it, took 20 minutes

**Comment by lhitori** [comment]
instantly reported to Interpol 🥶🏴‍☠️This software is under license which mean it's ❌illegal❌ to deobfuscate outputs! See you soon in court!!! 😡😡

**Comment by lhitori** [comment]
Joke apart, this is made to avoid AVs static analysis (I don't know if it still bypasses it though). Of course any obfuscator can be reversed with a bit of time. Nice to see there is 13 years olds that have good Python skills though.

**Comment by ImInTheICU** [comment]
> Joke apart, this is made to avoid AVs static analysis (I don't know if it still bypasses it though). Of course any obfuscator can be reversed with a bit of time. Nice to see there is 13 years olds that have good Python skills though.

Assuming the 13 year old part was satire.
Anyways its still very very cool!

**Comment by ImInTheICU** [comment]
> instantly reported to Interpol 🥶🏴‍☠️This software is under license which mean it's ❌illegal❌ to deobfuscate outputs! See you soon in court!!! 😡😡

Also i know this was a joke but... uhm the licenses ur using does not cover this.

**Comment by lhitori** [comment]
That literally the joke 🙏🙏 The 13 years old part wasn't satire.

**Comment by ImInTheICU** [comment]
> That literally the joke 🙏🙏 The 13 years old part wasn't satire.

U mad?
We deobfuscated it?

**Comment by lhitori** [comment]
No I'm not uh.
